const
    UPPER_ALPHABET = "QWERTYUIOPASDFGHJKLZXCVBNM",
    LOWER_ALPHABET = "qwertyuiopasdfghjklzxcvbnm",
    NUMBERS_ALPHABET = "0123456789",
    SYMBOLS_ALPHABET = ";:_,.-ç°§òàù@#é*è+[]{}|!\"£$%&/()=?^\\'ì<>",
    DEFAULT_ALPHABET = [UPPER_ALPHABET, LOWER_ALPHABET, NUMBERS_ALPHABET, SYMBOLS_ALPHABET]
;

exports.DEFAULT_ALPHABET = DEFAULT_ALPHABET;
